[project]
name = "genuary-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "einops>=0.8.0",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.0",
    "numpy<2",
    "scikit-image>=0.25.0",
    "scipy>=1.14.1",
]
